"""set default created_at on checklist_cards and card_variants

Revision ID: 5b78c4be1b9b
Revises: dc674d07a524
Create Date: 2026-03-11 11:33:43.969070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b78c4be1b9b'
down_revision: Union[str, Sequence[str], None] = 'dc674d07a524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_variants', 'autograph_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('card_variants', 'relic_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('card_variants', 'patch_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('card_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_cards', 'rookie_card',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('checklist_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklist_cards', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_cards', 'rookie_card',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card_variants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_variants', 'patch_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card_variants', 'relic_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card_variants', 'autograph_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
