"""set default created_at on products

Revision ID: dc674d07a524
Revises: 
Create Date: 2026-03-11 11:01:24.406256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc674d07a524'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_instances', 'condition_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('card_instances', 'serial_number_observed',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('card_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_variants', 'autograph_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card_variants', 'relic_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card_variants', 'patch_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_cards', 'player_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('checklist_cards', 'card_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('checklist_cards', 'rookie_card',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('checklist_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'manufacturer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('products', 'sport_or_universe',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sport_or_universe',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'manufacturer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('checklist_cards', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_cards', 'rookie_card',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('checklist_cards', 'card_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('checklist_cards', 'player_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('card_variants', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_variants', 'patch_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('card_variants', 'relic_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('card_variants', 'autograph_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('card_instances', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_instances', 'serial_number_observed',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('card_instances', 'condition_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
